name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 171.22.27.98
          port: 6886
          username: root
          password: Ashid6671?
          source: "*"
          target: "/home/ashidme/domains/ashid.ir/public_html/ai"
          rm: true
          
      - name: Execute commands on server
        uses: appleboy/ssh-action@master
        with:
          host: 171.22.27.98
          port: 6886
          username: root
          password: Ashid6671?
          script: |
            cd /home/ashidme/domains/ashid.ir/public_html/ai
            chown -R apache:apache .
            git pull origin main
            # اگر نیاز به نصب dependency دارید:
            # npm install
            # یا دستورات دیگر که نیاز دارید 